Repository UoaWDCC/uasc-web, pull requests merged in 2024-05, with the labels that each got.

#322 Cleanup env var usage for Stripe
  server/src/business-layer/services/StripeService.ts
  server/src/data-layer/environment.d.ts
  server/src/service-layer/controllers/StripeWebhook.ts
Labels: documentation, tech debt

#356 Update membership types, make membership selectable on frontend
  client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx
  client/src/components/generic/PricingCard/PricingCard.tsx
  client/src/firebase.ts
  client/src/models/__generated__/schema.d.ts
  client/src/services/AppData/AppDataService.ts
  client/src/services/Payment/PaymentQueries.ts
  client/src/services/Payment/PaymentService.ts
  client/src/services/QueryClient.ts
  client/src/store/MembershipPayment.tsx
  server/src/business-layer/utils/FirebaseErrorParser.ts
  server/src/business-layer/utils/StripeProductMetadata.ts
  server/src/middleware/__generated__/routes.ts
  server/src/middleware/__generated__/swagger.json
  server/src/middleware/routes.test.ts
  server/src/service-layer/controllers/PaymentController.ts
  server/src/service-layer/request-models/UserRequests.ts
Labels: backend, frontend

#377 Make workflow fail for frontend if there are TS errors
  client/package.json
  client/src/components/composite/AdminBookings/AdminBookings.tsx
  client/src/components/composite/AdminDetailedCalendar/AdminDetailedCalendar.tsx
  client/src/components/composite/Bookings/ProfileBookingHistory/ProfileBookingHistory.tsx
  client/src/components/composite/ContactForm/ContactForm.tsx
  client/src/components/composite/Event/Event.tsx
  client/src/components/generic/PricingCard/PricingCard.story.tsx
  client/src/pages/About.tsx
  client/src/pages/Admin.tsx
  client/src/pages/AdminBookingsDetailedView.tsx
  client/src/pages/Checkout.tsx
  client/src/pages/Contact.tsx
  client/src/pages/Events.tsx
  client/src/pages/Faq.tsx
  client/src/pages/Thanks.tsx
  client/src/routes/routes.tsx
Labels: improvement, tech debt

#370 Handle backend booking checkout
  package.json
  server/src/business-layer/services/AuthService.ts
  server/src/business-layer/services/StripeService.ts
  server/src/business-layer/utils/StripeProductMetadata.ts
  server/src/business-layer/utils/StripeSessionMetadata.ts
  server/src/business-layer/utils/UnreachableCase.ts
  server/src/data-layer/models/firebase.ts
  server/src/data-layer/services/BookingDataService.test.ts
  server/src/data-layer/services/BookingDataService.ts
  server/src/data-layer/services/BookingSlotsService.test.ts
  server/src/data-layer/services/BookingSlotsService.ts
  server/src/service-layer/controllers/PaymentController.ts
  server/src/service-layer/controllers/StripeWebhook.ts
  server/src/test-config/mocks/Stripe.mock.ts
Labels: backend
