Repository UoaWDCC/uasc-web, pull requests merged in 2024-06, with the labels that each got.

#384 Create members view for admin page with functionality implemented based on current backend endpoints
  client/src/assets/icons/three-dots-vertical.svg
  client/src/components/composite/Admin/AdminBookingDetails/AdminBookingDetails.tsx
  client/src/components/composite/Admin/AdminMemberView/AdminMemberView.story.tsx
  client/src/components/composite/Admin/AdminMemberView/AdminMemberView.test.tsx
  client/src/components/composite/Admin/AdminMemberView/AdminMemberView.tsx
  client/src/components/composite/Admin/AdminMemberView/AdminSearchBar.test.tsx
  client/src/components/composite/Admin/AdminMemberView/AdminSearchBar.tsx
  client/src/components/composite/Admin/AdminMemberView/ProtectedAdminMemberView.tsx
  client/src/components/composite/Admin/AdminNavbar/AdminNavbar.story.tsx
  client/src/components/composite/Admin/AdminNavbar/AdminNavbar.tsx
  client/src/components/composite/AdminNavbar/AdminNavbar.tsx
  client/src/components/composite/Navbar/AppNavbar.tsx
  client/src/components/composite/Navbar/Navbar.tsx
  client/src/components/composite/Navbar/utils/LoginIndicator.tsx
  client/src/components/composite/Navbar/utils/ProfileButton.tsx
  client/src/components/composite/Navbar/utils/WrappedTab.tsx
  client/src/components/generic/ReusableTable/Table.story.tsx
  client/src/components/generic/ReusableTable/Table.test.tsx
  client/src/components/generic/ReusableTable/Table.tsx
  client/src/components/generic/ReusableTable/TableFooterPaginator.tsx
  client/src/components/generic/ReusableTable/TableUtils.tsx
  client/src/components/utils/Utils.tsx
  client/src/pages/Admin.tsx
  client/src/pages/Admin/Admin.tsx
  client/src/routes/routes.tsx
  client/src/services/Admin/AdminMutations.ts
  client/src/services/Admin/AdminQueries.ts
  client/src/services/Admin/AdminService.ts
  client/src/services/User/UserMutations.ts
  client/src/services/User/UserService.ts
  server/src/business-layer/security/Authentication.ts
  server/tooling/login-prod.ts
Labels: frontend

#381 Backend endpoint for admins to make bookings available
  client/src/models/__generated__/schema.d.ts
  client/src/services/Admin/AdminService.ts
  server/src/business-layer/utils/BookingConstants.ts
  server/src/data-layer/adapters/DateUtils.test.ts
  server/src/data-layer/adapters/DateUtils.ts
  server/src/data-layer/adapters/FirestoreUtils.test.ts
  server/src/data-layer/adapters/FirestoreUtils.ts
  server/src/data-layer/services/BookingSlotsService.ts
  server/src/middleware/__generated__/routes.ts
  server/src/middleware/__generated__/swagger.json
  server/src/middleware/routes.test.ts
  server/src/service-layer/controllers/AdminController.ts
  server/src/service-layer/controllers/UserController.ts
  server/src/service-layer/request-models/AdminRequests.ts
  server/src/test-config/mocks/User.mock.ts
Labels: backend

#391 Allow admins to make dates unavailable using endpoint
  client/src/models/__generated__/schema.d.ts
  server/src/middleware/__generated__/routes.ts
  server/src/middleware/__generated__/swagger.json
  server/src/middleware/routes.test.ts
  server/src/service-layer/controllers/AdminController.ts
  server/src/service-layer/response-models/BookingResponse.ts
Labels: backend

#396 Allow make available endpoint to take in custom slots
  client/src/models/__generated__/schema.d.ts
  server/src/business-layer/utils/BookingConstants.ts
  server/src/middleware/__generated__/routes.ts
  server/src/middleware/__generated__/swagger.json
  server/src/middleware/routes.test.ts
  server/src/service-layer/controllers/AdminController.ts
  server/src/service-layer/request-models/AdminRequests.ts
Labels: improvement, backend

#402 338 endpoint all user bookings
  client/src/models/__generated__/schema.d.ts
  server/src/middleware/__generated__/routes.ts
  server/src/middleware/__generated__/swagger.json
  server/src/middleware/routes.test.ts
  server/src/service-layer/controllers/BookingController.ts
  server/src/service-layer/request-models/BookingRequests.ts
  server/src/service-layer/response-models/BookingResponse.ts
Labels: backend

#399 Fix bad input and close navbar on route change
  client/src/components/composite/Admin/AdminAvailabilityView/AdminAvailabilityView.tsx
  client/src/components/composite/Navbar/Navbar.tsx
Labels: tech debt

#416 HOT: add script to deal with tsoa swagger generation
  server/package.json
  server/tooling/remove-newlines.ts
Labels: bug, backend

#417 Refresh user tokens on pages that require it
  client/src/components/composite/SignUpForm/PageConfig/PageConfig.tsx
  client/src/hooks/useRefreshedToken.ts
  client/src/pages/Booking.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/pages/Register/Register.tsx
Labels: improvement, frontend

#430 fix overflow issues created by pricing cards
  client/src/components/composite/SignUpForm/Sections/PaymentSection.tsx
  client/src/components/generic/PricingCard/PricingCard.tsx
Labels: tech debt

#433 Booking payment endpoint frontend improvements
  client/src/models/__generated__/schema.d.ts
  server/src/middleware/__generated__/routes.ts
  server/src/middleware/__generated__/swagger.json
  server/src/service-layer/controllers/PaymentController.ts
  server/src/service-layer/request-models/UserRequests.ts
Labels: backend

#437 Improvements to profile and fixing confirmation dialog bug
  client/src/components/composite/SignUpForm/Sections/ConfirmationSection.tsx
  client/src/components/composite/SignUpForm/Sections/ContactSection.tsx
  client/src/components/generic/PricingCard/PricingCard.tsx
  client/src/models/__generated__/schema.d.ts
  client/src/pages/Profile/Profile.tsx
  client/src/store/SignUpForm.tsx
  server/src/data-layer/models/firebase.ts
  server/src/middleware/__generated__/routes.ts
  server/src/middleware/__generated__/swagger.json
  server/src/test-config/mocks/User.mock.ts
Labels: tech debt, frontend

#436 Allow for booking creation on frontend
  client/src/components/composite/Booking/BookingContext.tsx
  client/src/components/composite/Booking/BookingCreation/BookingCreation.story.tsx
  client/src/components/composite/Booking/BookingCreation/BookingCreation.test.tsx
  client/src/components/composite/Booking/BookingCreation/BookingCreation.tsx
  client/src/components/composite/Booking/BookingCreation/ProtectedCreateBookingSection.tsx
  client/src/components/composite/Booking/BookingInfoComponent/BookingInfoComponent.story.tsx
  client/src/components/composite/Booking/BookingInfoComponent/BookingInfoComponent.tsx
  client/src/components/composite/Booking/BookingPayment/BookingPayment.tsx
  client/src/components/composite/BookingCreation/BookingCreation.test.tsx
  client/src/components/composite/BookingCreation/BookingCreation.tsx
  client/src/components/composite/BookingCreation/ProtectedCreateBookingSection.tsx
  client/src/components/composite/Bookings/ProfileCurrentBookings/ProfileCurrentBookings.tsx
  client/src/components/composite/Navbar/Navbar.tsx
  client/src/components/generic/Checkbox/Checkbox.story.tsx
  client/src/components/generic/Checkbox/Checkbox.tsx
  client/src/components/utils/Utils.tsx
  client/src/firebase.ts
  client/src/hooks/useIsUserLoggedIn.ts
  client/src/hooks/useRefreshedToken.ts
  client/src/hooks/useUserLoggedInCallback.ts
  client/src/pages/Booking.tsx
  client/src/pages/BookingSuccess.tsx
  client/src/routes/routes.tsx
  client/src/services/Payment/PaymentMutations.ts
  client/src/services/Payment/PaymentQueries.ts
  client/src/services/Payment/PaymentService.ts
  client/src/services/User/UserMutations.ts
  client/src/services/User/UserService.ts
  client/src/services/Utils/Errors.ts
  server/src/business-layer/utils/StripeProductMetadata.ts
  server/src/business-layer/utils/StripeSessionMetadata.ts
Labels: frontend

#444 add optimistic mutations to promote and demote user mutations
  client/src/components/composite/Admin/AdminMemberView/ProtectedAdminMemberView.tsx
  client/src/models/User.ts
  client/src/models/__generated__/schema.d.ts
  client/src/services/Admin/AdminMutations.ts
  client/src/services/Admin/AdminQueries.ts
  client/src/services/Admin/AdminUtils.test.ts
  client/src/services/Admin/AdminUtils.ts
  server/src/middleware/__generated__/routes.ts
  server/src/middleware/__generated__/swagger.json
  server/src/service-layer/response-models/UserResponse.ts
Labels: improvement, tech debt, frontend

#462 Allow admins to delete users
  client/src/components/composite/Admin/AdminMemberView/AdminMemberView.tsx
  client/src/components/composite/Admin/AdminMemberView/ProtectedAdminMemberView.tsx
  client/src/components/generic/ReusableTable/Table.tsx
  client/src/services/Admin/AdminMutations.ts
  client/src/services/Admin/AdminService.ts
  server/src/service-layer/controllers/UserController.ts
Labels: frontend

#485 Fix date of birth input crashing site
  client/src/components/composite/SignUpForm/Sections/PersonalSection.tsx
Labels: bug

#484 Make profile sign out button work properly
  client/src/pages/Profile/Profile.tsx
Labels: bug

#488 properly set up prod deployments
  .github/workflows/deploy-client-dev.yml
  .github/workflows/deploy-server.production.yml
  .github/workflows/deploy-server.staging.yml
Labels: improvement

#483 Redirect user on password reset success
  client/src/components/composite/SignUpForm/Sections/AccountSetupSection.tsx
Labels: bug

#457 371 admin bookings view
  client/src/assets/icons/calender.svg
  client/src/components/composite/Admin/AdminBookingView/AdminBookingView.story.tsx
  client/src/components/composite/Admin/AdminBookingView/AdminBookingView.tsx
  client/src/components/composite/Admin/AdminBookingView/AdminBookingViewContext.tsx
  client/src/components/composite/Admin/AdminBookingView/WrappedAdminBookingView.tsx
  client/src/components/composite/Admin/AdminNavbar/AdminNavbar.tsx
  client/src/components/composite/Navbar/utils/WrappedTab.tsx
  client/src/components/generic/FigmaButtons/FigmaButton.tsx
  client/src/pages/Admin/Admin.tsx
  client/src/services/Admin/AdminQueries.ts
  client/src/services/Admin/AdminService.ts
Labels: frontend

#486 parse errors properly on log in form
  client/src/components/composite/LoginForm/LoginForm.tsx
  client/src/components/composite/LoginForm/PasswordResetForm/PasswordResetForm.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/utils/Handlers.tsx
Labels: bug

#466 Convert ALL dates sent to the backend to UTC
  client/src/components/composite/Admin/AdminAvailabilityView/AdminAvailabilityView.tsx
  client/src/components/composite/Admin/AdminAvailabilityView/DateSelectionContext.tsx
  client/src/components/composite/Admin/AdminAvailabilityView/WrappedAdminAvailabilityView.tsx
  client/src/components/composite/Admin/AdminBookingView/WrappedAdminBookingView.tsx
  client/src/components/composite/Booking/BookingContext.tsx
  client/src/components/composite/Booking/BookingCreation/BookingCreation.tsx
  client/src/components/composite/Booking/BookingCreation/ProtectedCreateBookingSection.tsx
  client/src/components/utils/DateUtils.test.tsx
  client/src/components/utils/DateUtils.tsx
  client/src/components/utils/Utils.tsx
  client/src/models/__generated__/schema.d.ts
  client/src/pages/Profile/Profile.tsx
  client/src/services/Admin/AdminMutations.ts
  server/src/business-layer/utils/BookingUtils.test.ts
  server/src/business-layer/utils/BookingUtils.ts
  server/src/data-layer/adapters/DateUtils.test.ts
  server/src/data-layer/adapters/DateUtils.ts
  server/src/data-layer/services/BookingDataService.test.ts
  server/src/data-layer/services/BookingDataService.ts
  server/src/data-layer/services/BookingSlotsService.ts
  server/src/middleware/__generated__/swagger.json
  server/src/middleware/routes.test.ts
  server/src/service-layer/controllers/AdminController.ts
  server/src/service-layer/controllers/PaymentController.ts
  server/src/service-layer/request-models/AdminRequests.ts
  server/src/service-layer/request-models/UserRequests.ts
Labels: tech debt, backend, frontend
